name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.8.3
homepage: https://github.com/cachapa/firedart

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: ^0.13.0
  grpc: ^3.0.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0
  googleapis_auth: ^1.0.0
  asn1lib: ^0.8.1
  pointycastle: ^2.0.1
  mime: ^1.0.0

dev_dependencies:
  test: ^1.16.3
  pedantic: ^1.10.0
