name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.8.3
homepage: https://github.com/cachapa/firedart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  grpc: ^3.0.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0
  googleapis_auth: ^1.1.0
  asn1lib: ^0.9.0-nullsafety.0
  pointycastle: ^3.0.0-nullsafety.2
  mime: ^1.0.0
  rxdart: ^0.26.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
